### ISSUE TITLE
Help getting started

### ISSUE THREAD

**Issue by art804** [madleech/FlickElectricApi#1]
Hi there, this package looks great - I just need a bit of a hand to get started...

I'd like to run this on my Raspberry Pi (running a Debian-based distro). Preferably from a bash shell script so I can then integrate it with Pushover to get notifications on certain price events.

I'm just not sure how I start with this code. Is this a package that I need to compile myself? Do I need to download the entire project to get going? Sorry but I'm a bit of a GitHub novice so it's not clear to me which language the code is written in, and how I go about invoking it from a bash command line.

Any tips or pointers to help get me going? Thanks in advance!

**Comment by scotty-p** [comment]
This is a library built in nodejs (a flavour of JavaScript). You will need to import this library into your application running nodejs code. As it is now, you will not be able to simply call this from the command line.

**Comment by art804** [comment]
OK, that explains why it seemed a bit unfamiliar to me. Thanks for the response.

**Comment by benjimons** [comment]
@ashtonaut if you are looking for cURL version you could rip it from my script

https://github.com/benjimons/flickphp/blob/master/flickjson.php

**Comment by art804** [comment]
Thanks! I'll check it out.
